name: 'Staqd'
description: 'Stacked PR merge queue powered by GitHub Actions and PR comments. No CLI, no SaaS.'
author: 'siner308'

branding:
  icon: 'git-merge'
  color: 'purple'

inputs:
  token:
    description: >
      GitHub token for API calls and git operations.
      Use a PAT or GitHub App token to enable CI auto-trigger after force push.
    required: false
    default: ${{ github.token }}
  app-id:
    description: 'GitHub App ID. Used with app-private-key to generate an installation token.'
    required: false
    default: ''
  app-private-key:
    description: 'GitHub App private key. Used with app-id to generate an installation token.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Generate GitHub App token
      id: app-token
      if: inputs.app-id != '' && inputs.app-private-key != ''
      continue-on-error: true
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-private-key }}

    # ── PR opened/edited: post stack guide ──
    - name: Post or update stack guide
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        ACTION_PATH: ${{ github.action_path }}
      with:
        github-token: ${{ steps.app-token.outputs.token || inputs.token }}
        script: |
          const guide = require(`${process.env.ACTION_PATH}/src/guide.js`);
          await guide({ github, context });

    # ── Comment: parse stack command ──
    - name: Parse command
      id: cmd
      if: github.event_name == 'issue_comment'
      uses: actions/github-script@v7
      with:
        script: |
          const body = context.payload.comment.body.trim();
          const match = body.match(
            /^(?:stack|st)\s+(merge-all|merge|restack|discover|help)\b(.*)$/i
          );
          if (!match) {
            core.setOutput('valid', 'false');
            return;
          }
          core.setOutput('valid', 'true');
          core.setOutput('command', match[1].toLowerCase());
          core.setOutput('force', String(match[2].includes('--force')));

    - name: React eyes
      if: steps.cmd.outputs.valid == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ steps.app-token.outputs.token || inputs.token }}
        script: |
          await github.rest.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: context.payload.comment.id,
            content: 'eyes',
          });

    - name: Checkout
      if: steps.cmd.outputs.valid == 'true' && steps.cmd.outputs.command != 'help' && steps.cmd.outputs.command != 'discover'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token || inputs.token }}

    - name: Configure git
      if: steps.cmd.outputs.valid == 'true' && steps.cmd.outputs.command != 'help' && steps.cmd.outputs.command != 'discover'
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Execute stack command
      if: steps.cmd.outputs.valid == 'true'
      id: run
      uses: actions/github-script@v7
      env:
        ACTION_PATH: ${{ github.action_path }}
        COMMAND: ${{ steps.cmd.outputs.command }}
        FORCE: ${{ steps.cmd.outputs.force }}
      with:
        github-token: ${{ steps.app-token.outputs.token || inputs.token }}
        script: |
          const command = require(`${process.env.ACTION_PATH}/src/command.js`);
          await command({
            github, context, core, exec,
            command: process.env.COMMAND,
            force: process.env.FORCE === 'true',
          });

    - name: Result reaction
      if: always() && steps.cmd.outputs.valid == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ steps.app-token.outputs.token || inputs.token }}
        script: |
          await github.rest.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: context.payload.comment.id,
            content:
              '${{ steps.run.outcome }}' === 'success'
                ? 'rocket'
                : 'confused',
          });
